### ISSUE TITLE
Had to abandon this tool

### ISSUE THREAD

**Issue by dy-fi** [foolin/goview#1]
This engine does not currently work(at least echo view) and had to be abandoned for a project I was working on.  You are not able to pass data from the handlers to the templates, instead it crashes the Echo app.  

I'm not sure if this is true of the other versions, but Echoview is unusable.

**Comment by foolin** [comment]
What's error?

**Comment by foolin** [comment]
Echo <=v3 version:
```bash
go get -u github.com/foolin/goview/supports/echoview
```

Echo v4 version:
```bash
go get -u github.com/foolin/goview/supports/echoview-v4
```

Example:
https://github.com/foolin/goview/tree/master/_examples/echo-v4
