### ISSUE TITLE
Additional funcs for templates

### ISSUE THREAD

**Issue by johndark** [foolin/goview#10]
Hello.

Please help with advice. I don’t understand how I can add a new function after initializing the config.
For example, if we take the example "/multiple/main.go"
we have two configs like `gvFront` and `gvBackend` initialized before route.
How I can add a new function `T` into handler like:
```
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		err := gvFront.Render(w, http.StatusOK, "index", goview.M{
			"title": "Frontend title!",
                        "T": func(id string) string { return "AAAAAAAAAA!" },
		})
		if err != nil {
			fmt.Fprintf(w, "Render index error: %v!", err)
		}
	})
```
If we run this code, we will see an error:
```
Render index error: ViewEngine render parser name:index,
error: template: index:2: function "T" not defined!
```
Adding a function in the process is a prerequisite,
I do not need this function at the initialization stage of the config.

**Comment by foolin** [comment]
you index.html template must write like this:
```
{{call $.T "id"}}
``

See  `tempConvertHTML` function: https://github.com/foolin/goview/tree/master/_examples/advance

**Comment by johndark** [comment]
> ```
> {{call $.T "id"}}
> ```
Thank you very much, you saved my brain! :)
