### ISSUE TITLE
How to parse html template in to echo render?

### ISSUE THREAD

**Issue by sayonnara** [foolin/goview#12]
Is there any option to parse some string like "{{.Title}}"?

Example
`return c.Render(http.StatusOK, `index`), echo.Map{"Render": "{{.Title}}"})`

**Comment by foolin** [comment]
you can see echo example.

**Comment by foolin** [comment]
https://github.com/foolin/goview/tree/master/supports/echoview

**Comment by ungvannara007** [comment]
In echo example when i passed "{{.Title}}" it will show "{{.Title}}" in webpage.
what I want is to show the value of title.
