### ISSUE TITLE
Could you tell me the difference between include tag and template tag?

### ISSUE THREAD

**Issue by saito-kosuke** [foolin/goview#13]
Could you tell me the difference?

`{{template "content" .}}`
`{{include "content"}}`

**Comment by foolin** [comment]
{{template "content" .}} is golang template syntax, see: https://golang.org/pkg/text/template/#hdr-Nested_template_definitions

```
`{{define "T1"}}ONE{{end}}
{{define "T2"}}TWO{{end}}
{{define "T3"}}{{template "T1"}} {{template "T2"}}{{end}}
{{template "T3"}}`
```
ouput:
```
ONE TWO
```


{{include "content"}} is goview function, the purpose is to support include files "~/views/content.html"

**Comment by saito-kosuke** [comment]
Thank you.
The goview doesn't make cache file by using include tag, does it?
We'd like to know the difference of cache structure between template tag and include tag.

**Comment by foolin** [comment]
include file will cache by default config `DisableCache:false`.  The Template Tag renders based on context variables, so not support cache.

**Comment by saito-kosuke** [comment]
Great!

As you know, you can use context variables by using include tag.
However, if a lot of users access the template using include tag, some users see the other user's context variables.
Could you tell me why?

**Comment by saito-kosuke** [comment]
Let me ask another question.
Could you tell me how to set the time to expire cache file?

**Comment by foolin** [comment]
Not expire time, it will in memory until your application stop runing.
