### ISSUE TITLE
Question about how to call a function

### ISSUE THREAD

**Issue by wsantos** [foolin/goview#16]
What is the diference about calling a function with/without `{{ call $.funname params }}`  ?

I've been trying to add the reverse URL function to the function and it only works without `call $.` but I'm not sure what it's right or wrong since this is not documented

My render
```
	//Set Renderer
	e.Renderer = echoview.New(goview.Config{
		Root:      "app/templates",
		Extension: ".html",
		Master:    "layouts/master",
		Partials:  []string{},
		Funcs: template.FuncMap{
			"reverse": e.Reverse,
		},
		DisableCache: false,
	})
```

This works
```
{{ reverse "board_create" }}
```

This throws an error
```
{{ call $.reverse "board_create" }}
```

Error: "ViewEngine execute template error: template: layouts/master:15:6: executing \"layouts/master\" at \u003cinclude \"layouts/header\"\u003e: error calling include: ViewEngine execute template error: template: layouts/header:15:23: executing \"layouts/header\" at \u003ccall $.reverse \"board_create\"\u003e: error calling call: call of nil"

**Comment by foolin** [comment]
### Global Function
If you register function by config (Global), you can call with `{{ reverse "board_create" }}`.
```go
goview.Config{
		Funcs: template.FuncMap{
			"reverse": e.Reverse,
		},
	}
```

### Temporary Function
If you don't register function by config, you also register by render data variable like this(Temporary):
```
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		err := goview.Render(w, http.StatusOK, "index", goview.M{
			"reverse": e.Reverse,
		})
		if err != nil {
			fmt.Fprintf(w, "Render index error: %v!", err)
		}
	})
```
Then you can call `{{ call $.reverse "board_create" }}` to use it.

**Comment by wsantos** [comment]
Thank you @foolin, do we have documentation for the template syntax? if so can you point me? I'd like to also know if we have some builtins like, range, ifs and etc, or do I need to provide it all through Funcmaps?

**Comment by foolin** [comment]
goview is base on golang/template, you see the official docuement: https://golang.org/pkg/text/template/#hdr-Functions

**Comment by wsantos** [comment]
@foolin Do you think would be better to document what you described? I can create a PR later today if you want to.

**Comment by foolin** [comment]
@wsantos  Of course, it would be nice to have template documentation,  welcome to submit your RP..
