### ISSUE TITLE
Auto complete Extensions

### ISSUE THREAD

**Issue by ArthurKnoep** [foolin/goview#2]
The file extension should not be added if it's already provided in the include instruction:

Example:  
I use the default configuration of goview, (so the Extensions is ".html")

error.html:
```
{{define "head"}}
    {{include "style.css"}}
{{end}}

{{define "content"}}
    <h1>Error</h1>
{{end}}
```

style.css:
```
body {
background-color: red;
}
```

The error I get:
```
ViewEngine execute template error: template: error:2:6: executing "head" at <include "style.css">: error calling include: ViewEngine render read name:style.css, path:<gopath>/github.com/<username>/<projectname>/service.web.oauth/views/style.css.html, error: open <gopath>/github.com/<username>/<projetctname>/service.web.oauth/views/style.css.html: no such file or directory
```

**Comment by foolin** [comment]
Oh, it’s a bug, Let me think how to fix this.

**Comment by foolin** [comment]
By the way, why you need include style css? You can't do like this to solve the problem.

-------------------------
1. Use link style css:

```
{{define "head"}}
   <link rel="stylesheet" type="text/css" href="/public/style.css" />
{{end}}

{{define "content"}}
    <h1>Error</h1>
{{end}}
```

-------------------------
2. Use base html template:

base.html
```html
<style type="text/css">
body {
background-color: red;
</style>
```

xxxx.html
```
{{include "base.html"}}
{{define "content"}}
    <h1>Error</h1>
{{end}}
```

**Comment by thiemdp** [comment]
hi foolin!
how to convert content (string) to hmtl us func in template?
thanks.

**Comment by foolin** [comment]
> hi foolin!
> how to convert content (string) to hmtl us func in template?
> thanks.

Please see this:
https://github.com/foolin/goview/issues/3

**Comment by ArthurKnoep** [comment]
It was only for the demonstration

**Comment by foolin** [comment]
if only for the demonstration, I close this issue now, if have any problem then reopen.
