### ISSUE TITLE
how to convert string to html in template

### ISSUE THREAD

**Issue by thiemdp** [foolin/goview#3]
am using {{.blog.Content | html}} but not working.
how to convert string to html in template?

**Comment by foolin** [comment]
You can look this docs: https://golang.org/pkg/html/template/, use `template.HTML` to convert html.

For examples:

1. Use template convert:
```
goview.Render(w, http.StatusOK, "index", goview.M{
			"Content": template.HTML(blog.Content),
		})
```

html template use: `{{.Content}}`

-------------------

2. Use global function:
```
goview.New(goview.Config{
		Root:      "views",
		Extension: ".tpl",
		Master:    "layouts/master",
		Partials:  []string{"partials/ad"},
		Funcs: template.FuncMap{
			"safeHTML": func(v string) template.HTML {
				return template.HTML(v)
			},
		},
		DisableCache: true,
	})
```
Then use `{{safeHTML .blog.Content}}`

-------------------

3. Use current page function:
```
goview.Render(w, http.StatusOK, "index", goview.M{
			"tempConvertHTML": func(v string) template.HTML {
				return template.HTML(v)
			},
		})
```
Then use `{{call $.tempConvertHTML .blog.Content}}`

-------------------

I update the example for this: 
https://github.com/foolin/goview/tree/master/_examples/advance

**Comment by thiemdp** [comment]
thankyou very much!
