### ISSUE TITLE
no matching versions for query "latest"

### ISSUE THREAD

**Issue by thiemdp** [foolin/goview#4]
hi foolin!
am using echov4
am run with cmd: go get -u github.com/foolin/goview/supports/echoview-v4
Error:
go: finding github.com/foolin/goview/supports/echoview-v4 latest
go: finding github.com/foolin/goview/supports latest
go get github.com/foolin/goview/supports/echoview-v4: no matching versions for query "latest"
can you help me? thanks!

**Comment by foolin** [comment]
please try add version?

```
go get -u github.com/foolin/goview/supports/echoview-v4@0.2.1
```

**Comment by foolin** [comment]
No feedback, closed.
