### ISSUE TITLE
How can i use go.rice in gin via goview, like git-template

### ISSUE THREAD

**Issue by palytoxin** [foolin/goview#7]
gorice and gin is work fine in [foolin/gin-template](https://github.com/foolin/gin-template/blob/master/examples/gorice/main.go)

`router.HTMLRender = gorice.New(rice.MustFindBox("views"))`

but now, I will use go.rice via goview, built app throw error no such file or directory

```
panic recovered:
ViewEngine render read name:base/master, path:/tmp/templates/views/base/master.tmpl, error: open /tmp/templates/views/base/master.tmpl: no such file or directory
```

I think go.rice is not working.

my code:
```
r := gin.Default()

staticBox := rice.MustFindBox("templates/static")
viewBox := rice.MustFindBox("templates/views")
r.StaticFS("/static", staticBox.HTTPBox())

gv := gorice.NewWithConfig(viewBox, goview.Config{
  Root:      "templates/views",
  Extension: ".tmpl",
  Master:    "base/master",
})
goview.Use(gv)

r.HTMLRender = ginview.New(goview.Config{
  Root:      "templates/views",
  Extension: ".tmpl",
  Master:    "base/master",
})

r.GET("/", func(c *gin.Context) {
	ginview.HTML(c, http.StatusOK, "index", gin.H{
		"title":                  "Gin",
		"ginBladeManagerVersion": "v1",
		"goVersion":              runtime.Version(),
	})
})
```
How do I make gorice work in gin via goview?

**Comment by esosan** [comment]
@palytoxin  do you found a solution to goview-gorice integration? I have the same problem...

**Comment by foolin** [comment]
Add support and examples:

https://github.com/foolin/goview/tree/master/_examples/gin-rice

@esosan @palytoxin

**Comment by palytoxin** [comment]
> @palytoxin do you found a solution to goview-gorice integration? I have the same problem...

Last month, I used the goview.Render method directly before. Not using HTMLRender。。。 but now the maintainer came up with a better solution. 



> Add support and examples:
> 
> https://github.com/foolin/goview/tree/master/_examples/gin-rice
> 
> Please update the new version: v0.3.0
> 
> @esosan @palytoxin


I am so grateful

**Comment by esosan** [comment]
Thank you!
