### ISSUE TITLE
Compile templates into server executable

### ISSUE THREAD

**Issue by josegonzalez** [foolin/goview#9]
Not sure if this is possible, but I'm trying to compile the templates/static files into the binary so that when I run the executable elsewhere, I don't also have to figure out how to ship assets - that is to say, it's all included within the compiled go binary.

I've done this before with static assets utilizing [go-bindata](https://github.com/go-bindata/go-bindata#serve-assets-with-nethttp), but not sure if there is a way to do it for goview.

In my case, I'm specifically utilizing goview with gin (via ginview) but hopefully that doesn't impact the answer.

Great work btw, this package looks awesome!

**Comment by foolin** [comment]
Use gorice for compile to application.

**Comment by foolin** [comment]
Example:

https://github.com/foolin/goview/tree/master/_examples/gorice

Go.Rice:
https://github.com/GeertJohan/go.rice

**Comment by josegonzalez** [comment]
Awesome I got it working.

For anyone replicating the above, one thing to note is that all partials specified _must_ exist, otherwise you may get a "file does not exist" error, regardless of whether that partial exists in your code or not.

Thanks @foolin for your work on this project and the examples, its super awesome!
